name = "spin-mama-bonus-fr"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spin-mama-bonus.fr"
HMAC_KEY = "58608b912c1b19f8277c431e589224560a0f7d9c67194d5352933978db2c7c88"
COOKIE_NAME = "p70"
PLAY_PATH = "begin"
BUTTON_ID = "p0ad1c0fa6bbb04e7d8f03b3550a6f42d"
GATE_SALT = "3e1ef920b5693696"
